# Generated by Django 4.0.6 on 2022-07-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='throw',
            field=models.ManyToManyField(blank=True, to='anime.throw'),
        ),
    ]
